name: "rebase development and release from master"
on:
  workflow_call:
    inputs:
      is-executable:
        description: ""
        required: true
        type: boolean
    secrets:
      github-token:
        description: "The token to use for the release"
        required: true
      gpg-sign-key:
        description: "The private key to sign artifacts"
        required: true
      gpg-key-passphrase:
        description: "The passphrase to unlock the private key"
        required: true
      gpg-key-fingerprint:
        description: "The fingerprint of the key"
        required: true
jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - uses: asperan/actions-merge-push@v1
        with:
          from-branch: "development"
          to-branch: "main"
          merge-type: "rebase"
      - uses: asperan/actions-dlang-release@7c52298ef516902e755af9a940ee644698d918ca
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          is-executable: true
          gpg-sign-key: ${{ secrets.gpg-sign-key }}
          gpg-key-passphrase: ${{ secrets.gpg-key-passphrase }}
          gpg-key-fingerprint: ${{ secrets.gpg-key-fingerprint }}
