name: "rebase development and release from master"
on:
  workflow_call:
    inputs:
      is-executable:
        description: ""
        required: true
        type: boolean
    secrets:
      github-token:
        description: "The token to use for the release"
        required: true
jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - uses: asperan/actions-merge-push@v1
        with:
          from-branch: "development"
          to-branch: "main"
          merge-type: "rebase"
      - uses: asperan/actions-dlang-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          is-executable: true
